# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"H\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"7\n\rConfigRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"I\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"8\n\x0e\x43onfigResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t2\x8d\x04\n\x0f\x44\x61tabaseService\x12;\n\nCreateUser\x12\x15.database.UserRequest\x1a\x16.database.UserResponse\x12\x39\n\x08ReadUser\x12\x15.database.UserRequest\x1a\x16.database.UserResponse\x12;\n\nUpdateUser\x12\x15.database.UserRequest\x1a\x16.database.UserResponse\x12;\n\nDeleteUser\x12\x15.database.UserRequest\x1a\x16.database.UserResponse\x12\x41\n\x0c\x43reateConfig\x12\x17.database.ConfigRequest\x1a\x18.database.ConfigResponse\x12?\n\nReadConfig\x12\x17.database.ConfigRequest\x1a\x18.database.ConfigResponse\x12\x41\n\x0cUpdateConfig\x12\x17.database.ConfigRequest\x1a\x18.database.ConfigResponse\x12\x41\n\x0c\x44\x65leteConfig\x12\x17.database.ConfigRequest\x1a\x18.database.ConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=28
  _globals['_USERREQUEST']._serialized_end=100
  _globals['_CONFIGREQUEST']._serialized_start=102
  _globals['_CONFIGREQUEST']._serialized_end=157
  _globals['_USERRESPONSE']._serialized_start=159
  _globals['_USERRESPONSE']._serialized_end=232
  _globals['_CONFIGRESPONSE']._serialized_start=234
  _globals['_CONFIGRESPONSE']._serialized_end=290
  _globals['_DATABASESERVICE']._serialized_start=293
  _globals['_DATABASESERVICE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
