version: "3.9"
services:
  application:
	build:
	  context: ./application
	  dockerfile: Dockerfile
	ports:
	  - "5000:5000"
	environment:
	  APPLICATION_SECRET_KEY: ${APPLICATION_SECRET_KEY}
	  SIMULATOR_PORT: ${SIMULATOR_PORT}
	depends_on:
	  - simulator

  simulator:
	build:
	  context: ./simulator
	  dockerfile: Dockerfile
	ports:
	  - "50052:50052"
	environment:
	  OPENAI_API_KEY: ${OPENAI_API_KEY}
	  PORT: ${PORT}


